import { toImports } from 'unimport'
import MagicString from 'magic-string'
import { createWriteStream, readFileSync, writeFileSync } from 'node:fs'

const file = createWriteStream('unimport.js', { flags: 'w' })

file.write(`/* eslint-disable eslint-comments/no-unlimited-disable */
/* eslint-disable */

// generated by nuxt-undo-autoimports
`)

export async function saveTransformation(id, matchedImports, options) {
  if (!id.match(/[\\/]node_modules[\\/]/) && !id.match(/^virtual:/)) {
    const isVue = id.match(/\?vue/)
    const imports = new MagicString(toImports(matchedImports))
    if (options.cwdAlias) {
      imports.replaceAll(process.cwd(), options.cwdAlias)
    }
    file.write(`// ${id.replace(/\?.*/, '')}
${imports.toString()}

`)
    if (options.mode === 'log') {
        return
    }
    if (options.mode === 'comment') {
        imports.prepend('/* generated by nuxt-undo-autoimports\n')
        imports.append('\n*/')
    }
    imports.append('\n')
    if (id.match('/home/user/movies/app.vue')) {
      const file = readFileSync(id.replace(/\?.*/, ''), 'utf-8')
      const code = new MagicString(file)
      if (isVue) {
        code.replace(/(<script[^><]*>)/gm, `$1
${imports.toString()}`)
      } else {
        code.prepend(imports.toString())
      }
      writeFileSync(id, code.toString())
    }
  }
}
